controllers/AuthenticationController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\logics\UserManager;
use app\models\RegistrationForm;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\db\Exception;
use app\models\Profile;

class AuthenticationController extends Controller{
    private $loginForm;
    private $registrationForm;
    
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->loginForm = new LoginForm();
        $this->registrationForm = new RegistrationForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
     
    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->request->isAjax && $this->loginForm->load(Yii::$app->request->post())) {
              if($this->loginForm->validate()){
                $manager = new UserManager();
                if($manager->Login($this->loginForm)){ $this->goHome();}
                else{  
                    $this->loginForm->addError("login","User with such password and username does not exist.");
                    return $this->render('//site/login',["model"=>$this->loginForm]);  
                 }
              }
              else{ return $this->render('//site/login',["model"=>$this->loginForm]); }
        } 
        else{ $this->render('//site/login',["model"=>$this->loginForm]); }
    }
 
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->goHome();
    }
    
    public function actionRegistration(){
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->request->isAjax && $this->registrationForm->load(Yii::$app->request->post())) {
          if($this->registrationForm->validate()){
                $manager = new UserManager();
                try{
                    $manager->Registration($this->registrationForm->login, $this->registrationForm->password);
                    $this->loginForm->login = $this->registrationForm->login;
                    $this->loginForm->password = $this->registrationForm->password;
                    $this->loginForm->rememberMe = false;
                    $manager->Login($this->loginForm);
                    $profile = new Profile();
                    $profile->user_id = Yii::$app->user->id;
                    $profile->save();
                    return $this->goHome();
                }
                catch(Exception $ex){
                    $this->registrationForm->addError("login","A user with this login already exists. Try another.");
                    return $this->render('//site/registration',['model'=>$this->registrationForm]);
                }   
            }
            else{ return $this->render('//site/registration',['model'=>$this->registrationForm]); }   
        }
        else{ return $this->render('//site/registration',['model'=>$this->registrationForm]); }
        
    }
}

controllers/BulletinController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\AddBulletinForm;
use app\models\Bulletin;
use Yii;
use yii\web\UploadedFile;

class BulletinController extends Controller{
    
    private $addBulletinForm;

    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->addBulletinForm = new AddBulletinForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function actionIndex(){
         return $this->render('addBulletin',['model' => $this->addBulletinForm] );
    }

    public function actionAddbulletin() {
        if(Yii::$app->request->post()){
              if($this->addBulletinForm->load(Yii::$app->request->post()) && $this->addBulletinForm->validate()){ 
                    $bulletin = new Bulletin();
                    $bulletin->user_id = Yii::$app->user->id;
                    $bulletin->title = $this->addBulletinForm->title;
                    $bulletin->date = strftime('%Y-%m-%d %H:%M:%S',$_SERVER['REQUEST_TIME']);
                    $bulletin->body = $this->addBulletinForm->body;
                    $bulletin->price = $this->addBulletinForm->price;
                    $file = UploadedFile::getInstance($this->addBulletinForm,'title_image');
                    if($file){
                        $imagePath = $file->baseName . '.' . $file->extension;
                        $file->saveAs('uploads/' . $imagePath);
                        $bulletin->title_image = $imagePath;  
                    }
                    try{
                      $bulletin->save();
                      $this->goHome();  
                    }  catch (Exception $ex){
                        $this->render('addBulletin',['model' => $this->addBulletinForm] );
                    }
                  }
                  else{return $this->render('addBulletin',['model' => $this->addBulletinForm]);}
              }
              else{
                  return $this->render('addBulletin',['model' => $this->addBulletinForm] );
              }  
      }
      
    public function actionSelect($id){
        $bulletin = Bulletin::find()
                ->where(["id"=>$id])->one();
        return $this->render('showBulletin',['bulletin' => $bulletin]);
    }
}

controllers/ProfileController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\EditProfileForm;
use app\models\Profile;
use Yii;
use yii\web\UploadedFile;
use app\models\AddComentForm;
use app\models\Comment;
use app\models\AddRatingForm;
use app\models\Rating;
use yii\helpers\Url;

class ProfileController extends Controller{
    
    private $profileForm;
    private $profile;
    private $addCommentForm;
    private $addRatingForm;
            
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->profileForm = new EditProfileForm();
        $this->addCommentForm = new AddComentForm();
        $this->addRatingForm = new AddRatingForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function actionIndex(){
        $profile = Profile::find()->where(['user_id'=>Yii::$app->user->id])->one();
        if($profile){
            $this->profileForm->name = $profile->name;
            $this->profileForm->email = $profile->email;
            $this->profileForm->phone = $profile->phone;
            $this->profileForm->skype = $profile->skype;
            $this->profileForm->location = $profile->location;
            $this->profileForm->photo = $profile->photo;
        }
        return $this->render('editProfile', ['model' => $this->profileForm]);  
    }

    public function actionEditprofile(){
        $profile = Profile::find()->where(['user_id'=>Yii::$app->user->id])->one();
        if($profile){
            $this->profileForm->name = $profile->name;
            $this->profileForm->email = $profile->email;
            $this->profileForm->phone = $profile->phone;
            $this->profileForm->skype = $profile->skype;
            $this->profileForm->location = $profile->location;
            $this->profileForm->photo = $profile->photo;
        }
            if(Yii::$app->request->post()){
                    if($this->profileForm->load(Yii::$app->request->post()) && $this->profileForm->validate()){  
                       $profile = Profile::find()->where(['user_id' => Yii::$app->user->id])->one();
                       $profile->user_id = Yii::$app->user->id;
                       $profile->name = $this->profileForm->name;
                       $profile->email = $this->profileForm->email;
                       $profile->phone = $this->profileForm->phone;
                       $profile->skype = $this->profileForm->skype;
                       $profile->location = $this->profileForm->location;
                       $image = UploadedFile::getInstance($this->profileForm,'photo');
                            if($image){
                                $profile->photo = base64_encode(file_get_contents($image->tempName));
                            }
                           try{$profile->save();}
                           catch (Exception $ex){return $this->render('editProfile',['model' => $this->profileForm] ); }
                                 return $this->refresh(); 
                            }  
                             else{
                                 return $this->render('editProfile',['model' => $this->profileForm] ); 
                             } 
               }
        else{
              return $this->render('editProfile', ['model' => $this->profileForm]);  
       }
    }
    
    public function actionSelect($id){
       $this->profile =  Profile::find()
                  ->where(["profile.user_id"=>$id]) 
                  ->with('bulletins')
                  ->with('comments')
                  ->one();
       $this->profile->comments;
       return $this->render('showProfile',['profile' => $this->profile,
           "commentModel"=>$this->addCommentForm,
           "ratingModel"=>$this->addRatingForm] ); 
    }
   
    public function actionAddcomment(){
          $coment = new Comment();
          if($this->addCommentForm->load(Yii::$app->request->post()) && $this->addCommentForm->validate()){
           $coment->body = $this->addCommentForm->body;
           $coment->date = strftime('%Y-%m-%d %H:%M:%S',$_SERVER['REQUEST_TIME']);
           $coment->author_id = Yii::$app->user->id;
           $coment->user_id = $this->addCommentForm->user_id;
           try{
               $coment->save();
               return $this->redirect(Url::to(['select', 'id' => $this->addCommentForm->user_id]));
           }
           catch (Exception $ex){ 
              return $this->refresh();
           }
        } 
        else{ return $this->goBack();}   
      }  
      
    public function actionAddrating(){
          $rating = new Rating();
          if($this->addRatingForm->load(Yii::$app->request->post()) && $this->addRatingForm->validate()){
           $rating->rating = $this->addRatingForm->rating;
           $rating->author_id = Yii::$app->user->id;
           $rating->user_id = $this->addRatingForm->user_id;
           try{
               $rating->save();
               return $this->redirect(Url::to(['select', 'id' => $this->addRatingForm->user_id]));
           }
           catch (Exception $ex){ return $this->refresh();}
        } 
        else{ return $this->goBack();}     
      }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\Bulletin;
use yii\data\Pagination;

class SiteController extends Controller{
 
    private $bulletins;
    private $bulletinsPages;

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()  {
        $this->bulletins = Bulletin::find();
        $countQuery = clone $this->bulletins;
        $this->bulletinsPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>20]);
        $this->bulletins= $this->bulletins->offset($this->bulletinsPages->offset)
                 ->limit($this->bulletinsPages->limit)
                 ->orderBy([
                    'date' => SORT_DESC
                  ])
                 ->all();
        return $this->render('index',['bulletins'=>$this->bulletins,"bulletinsPages"=>$this->bulletinsPages]);
    }

    public function actionLogin(){
        return $this->render('login',['model'=>new LoginForm()]);
     }
     
    public function actionRegistration(){
        return $this->render('registration',['model'=> new RegistrationForm()]);
     }  
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="img/logo.png" rel="icon">
    
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
  <div class="wrap">
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="<?php echo Yii::$app->urlManager->createUrl(['site/index']);?>">Bulletin<span>Board</span></a></h1>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->
    
    <?php
    NavBar::begin([
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'mainmenu-area',
        ],
    ]);
     echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Bulletin board', 'url' => ['/site/index']],
        ],
    ]);
    
    $menuItems = [];
    if(Yii::$app->user->isGuest){
        $menuItems[] = ['label' => 'Login','url' => ['/site/login']];
        $menuItems[] = ['label' => 'Registration','url' => ['/site/registration']]; 
    }
    else{
        $menuItems[] = ['label' => 'Add advert','url' => ['/bulletin/index']]; 
        $menuItems[] = ['label' => 'My profile','url' => ['/profile/index']]; 
        $menuItems[] = ['label' => 'LogOut', 'url' => ['/authentication/logout']];  
    }
    
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems
    ]);  
    
    NavBar::end();
    ?>
    
     <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2><?= Html::encode($this->title) ?></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
    
<div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="copyright">
                        <p>&copy; 2016 Bulletin board. All Rights Reserved.</p>
                    </div>
                </div> 
            </div>
        </div>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>