controllers/BulletinController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\AddBulletinForm;
use app\models\Bulletin;
use Yii;
use yii\web\UploadedFile;

class BulletinController extends Controller{
    
    private $addBulletinForm;

    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->addBulletinForm = new AddBulletinForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function actionIndex(){
         return $this->render('addBulletin',['model' => $this->addBulletinForm] );
    }

    public function actionAddbulletin() {
        if(Yii::$app->request->post()){
              if($this->addBulletinForm->load(Yii::$app->request->post()) && $this->addBulletinForm->validate()){ 
                    $bulletin = new Bulletin();
                    $bulletin->user_id = Yii::$app->user->id;
                    $bulletin->title = $this->addBulletinForm->title;
                    $bulletin->date = strftime('%Y-%m-%d %H:%M:%S',$_SERVER['REQUEST_TIME']);
                    $bulletin->body = $this->addBulletinForm->body;
                    $bulletin->price = $this->addBulletinForm->price;
                    $file = UploadedFile::getInstance($this->addBulletinForm,'title_image');
                    if($file){
                        $imagePath = $file->baseName . '.' . $file->extension;
                        $file->saveAs('uploads/' . $imagePath);
                        $bulletin->title_image = $imagePath;  
                    }
                    try{
                      $bulletin->save();
                      $this->goHome();  
                    }  catch (Exception $ex){
                        $this->render('addBulletin',['model' => $this->addBulletinForm] );
                    }
                  }
                  else{return $this->render('addBulletin',['model' => $this->addBulletinForm]);}
              }
              else{
                  return $this->render('addBulletin',['model' => $this->addBulletinForm] );
              }  
      }
      
    public function actionSelect($id){
        $bulletin = Bulletin::find()
                ->where(["id"=>$id])->one();
        return $this->render('showBulletin',['bulletin' => $bulletin]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\Bulletin;
use yii\data\Pagination;

class SiteController extends Controller{
 
    private $bulletins;
    private $bulletinsPages;

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()  {
        $this->bulletins = Bulletin::find();
        $countQuery = clone $this->bulletins;
        $this->bulletinsPages = new Pagination(['totalCount' => $countQuery->count(),'pageSize'=>20]);
        $this->bulletins= $this->bulletins->offset($this->bulletinsPages->offset)
                 ->limit($this->bulletinsPages->limit)
                 ->orderBy([
                    'date' => SORT_DESC
                  ])
                 ->all();
        return $this->render('index',['bulletins'=>$this->bulletins,"bulletinsPages"=>$this->bulletinsPages]);
    }

    public function actionLogin(){
        return $this->render('login',['model'=>new LoginForm()]);
     }
     
    public function actionRegistration(){
        return $this->render('registration',['model'=> new RegistrationForm()]);
     }  
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\widgets\LinkPager;
use yii\helpers\Html;
$this->title = 'Bulletin board';
?>
    <div class="single-product-area">
        <div class="container">
            <?php 
            foreach ($bulletins as $bulletin){  
               echo"   <div class='col-md-3 col-sm-6'>
                    <div class='single-shop-product'>
                        <div class='product-upper'>".
                            Html::img('@web/uploads/'.$bulletin->title_image).
                        "</div>
                        <h2>$bulletin->title</h2>
                        <div class='product-carousel-price'>
                            <ins>$$bulletin->price</ins>
                        </div>  
                        <div class='product-option-shop'>".
                           Html::a("More...",['bulletin/select', 'id' =>$bulletin->id ] ,['data-pjax'=>0,"class"=>"add_to_cart_button"])."
                        </div>                       
                    </div>
                </div> ";    
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <div class="product-pagination text-center">
                        <nav>
                            <?php  
                           echo LinkPager::widget([
                                'pagination' => $bulletinsPages,
                                'options'=>["class"=>"pagination"]
                           ]); 
                         ?>        
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

views/site/login.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
$this->title = 'Log in';
?>
<div class="container">
    <div class="col-md-offset-4 col-md-4 center-form">
       
              <?php Pjax::begin(['timeout' => 5000]); ?>
                 <?php $form = ActiveForm::begin([
                             'id' => 'login-form',
                             'method' => 'post',
                             'action' => ['authentication/login'],
                             'options' => ['onsubmit' => 'return false','data-pjax' => true],
                             'enableClientValidation' => true,
                              ]); ?>
            
                  <div class="form-group">
                       <?= $form->field($model, 'login')->label("Login") ?>
                  </div>
                  <div class="form-group">
                       <?= $form->field($model, 'password')->passwordInput()->label("Password") ?>
                  </div> 
                  <div class="form-group">
                       <?= $form->field($model, 'rememberMe')->checkbox() ?>
                  </div>
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary" id="login-btn">LogIn</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Clear</button>
                  </div>
                 <?php ActiveForm::end(); ?>
              <?php Pjax::end(); ?>
   
    </div>
</div>
            
           

views/site/registration.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
$this->title = 'Registration';
?>
<div class="container">
    <div class="col-md-offset-4 col-md-4 center-form">
        
              <?php Pjax::begin(['timeout' => 5000]); ?>
                 <?php $form = ActiveForm::begin([
                             'id' => 'login-form',
                             'method' => 'post',
                             'action' => ['authentication/registration'],
                             'options' => ['onsubmit' => 'return false','data-pjax' => true],
                             'enableClientValidation' => true,
                              ]); ?>
            
                  <div class="form-group">
                       <?= $form->field($model, 'login')->label("Login") ?>
                  </div>
                  <div class="form-group">
                       <?= $form->field($model, 'password')->passwordInput()->label("Password") ?>
                  </div>         
                  <div class="form-group">
                       <?= $form->field($model, 'confirmPassword')->passwordInput()->label("ConfirmPassword") ?>
                  </div>  
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary" id="login-btn">Registrtion</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Clear</button>
                  </div>
        
                 <?php ActiveForm::end(); ?>
              <?php Pjax::end(); ?>

    </div>
</div>
            
           