models/Bulletin.php
<?php

namespace app\models;
use yii\db\ActiveRecord;

class Bulletin extends ActiveRecord 
{
    private $user_id;
    private $id;
    private $date;
    private $title;
    private $body;
    private $price;
    private $title_image;
    
    public static function tableName(){
        return 'bulletin';
    }
}  


    

controllers/BulletinController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\AddBulletinForm;
use app\models\Bulletin;
use Yii;
use yii\web\UploadedFile;

class BulletinController extends Controller{
    
    private $addBulletinForm;

    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->addBulletinForm = new AddBulletinForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function actionIndex(){
         return $this->render('addBulletin',['model' => $this->addBulletinForm] );
    }

    public function actionAddbulletin() {
        if(Yii::$app->request->post()){
              if($this->addBulletinForm->load(Yii::$app->request->post()) && $this->addBulletinForm->validate()){ 
                    $bulletin = new Bulletin();
                    $bulletin->user_id = Yii::$app->user->id;
                    $bulletin->title = $this->addBulletinForm->title;
                    $bulletin->date = strftime('%Y-%m-%d %H:%M:%S',$_SERVER['REQUEST_TIME']);
                    $bulletin->body = $this->addBulletinForm->body;
                    $bulletin->price = $this->addBulletinForm->price;
                    $file = UploadedFile::getInstance($this->addBulletinForm,'title_image');
                    if($file){
                        $imagePath = $file->baseName . '.' . $file->extension;
                        $file->saveAs('uploads/' . $imagePath);
                        $bulletin->title_image = $imagePath;  
                    }
                    try{
                      $bulletin->save();
                      $this->goHome();  
                    }  catch (Exception $ex){
                        $this->render('addBulletin',['model' => $this->addBulletinForm] );
                    }
                  }
                  else{return $this->render('addBulletin',['model' => $this->addBulletinForm]);}
              }
              else{
                  return $this->render('addBulletin',['model' => $this->addBulletinForm] );
              }  
      }
      
    public function actionSelect($id){
        $bulletin = Bulletin::find()
                ->where(["id"=>$id])->one();
        return $this->render('showBulletin',['bulletin' => $bulletin]);
    }
}

controllers/ProfileController.php
<?php
namespace app\controllers;

use yii\web\Controller;
use app\models\EditProfileForm;
use app\models\Profile;
use Yii;
use yii\web\UploadedFile;
use app\models\AddComentForm;
use app\models\Comment;
use app\models\AddRatingForm;
use app\models\Rating;
use yii\helpers\Url;

class ProfileController extends Controller{
    
    private $profileForm;
    private $profile;
    private $addCommentForm;
    private $addRatingForm;
            
    function __construct($id, $module){
        parent::__construct($id, $module);
        $this->profileForm = new EditProfileForm();
        $this->addCommentForm = new AddComentForm();
        $this->addRatingForm = new AddRatingForm();
     }
     
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
    
    public function actionIndex(){
        $profile = Profile::find()->where(['user_id'=>Yii::$app->user->id])->one();
        if($profile){
            $this->profileForm->name = $profile->name;
            $this->profileForm->email = $profile->email;
            $this->profileForm->phone = $profile->phone;
            $this->profileForm->skype = $profile->skype;
            $this->profileForm->location = $profile->location;
            $this->profileForm->photo = $profile->photo;
        }
        return $this->render('editProfile', ['model' => $this->profileForm]);  
    }

    public function actionEditprofile(){
        $profile = Profile::find()->where(['user_id'=>Yii::$app->user->id])->one();
        if($profile){
            $this->profileForm->name = $profile->name;
            $this->profileForm->email = $profile->email;
            $this->profileForm->phone = $profile->phone;
            $this->profileForm->skype = $profile->skype;
            $this->profileForm->location = $profile->location;
            $this->profileForm->photo = $profile->photo;
        }
            if(Yii::$app->request->post()){
                    if($this->profileForm->load(Yii::$app->request->post()) && $this->profileForm->validate()){  
                       $profile = Profile::find()->where(['user_id' => Yii::$app->user->id])->one();
                       $profile->user_id = Yii::$app->user->id;
                       $profile->name = $this->profileForm->name;
                       $profile->email = $this->profileForm->email;
                       $profile->phone = $this->profileForm->phone;
                       $profile->skype = $this->profileForm->skype;
                       $profile->location = $this->profileForm->location;
                       $image = UploadedFile::getInstance($this->profileForm,'photo');
                            if($image){
                                $profile->photo = base64_encode(file_get_contents($image->tempName));
                            }
                           try{$profile->save();}
                           catch (Exception $ex){return $this->render('editProfile',['model' => $this->profileForm] ); }
                                 return $this->refresh(); 
                            }  
                             else{
                                 return $this->render('editProfile',['model' => $this->profileForm] ); 
                             } 
               }
        else{
              return $this->render('editProfile', ['model' => $this->profileForm]);  
       }
    }
    
    public function actionSelect($id){
       $this->profile =  Profile::find()
                  ->where(["profile.user_id"=>$id]) 
                  ->with('bulletins')
                  ->with('comments')
                  ->one();
       $this->profile->comments;
       return $this->render('showProfile',['profile' => $this->profile,
           "commentModel"=>$this->addCommentForm,
           "ratingModel"=>$this->addRatingForm] ); 
    }
   
    public function actionAddcomment(){
          $coment = new Comment();
          if($this->addCommentForm->load(Yii::$app->request->post()) && $this->addCommentForm->validate()){
           $coment->body = $this->addCommentForm->body;
           $coment->date = strftime('%Y-%m-%d %H:%M:%S',$_SERVER['REQUEST_TIME']);
           $coment->author_id = Yii::$app->user->id;
           $coment->user_id = $this->addCommentForm->user_id;
           try{
               $coment->save();
               return $this->redirect(Url::to(['select', 'id' => $this->addCommentForm->user_id]));
           }
           catch (Exception $ex){ 
              return $this->refresh();
           }
        } 
        else{ return $this->goBack();}   
      }  
      
    public function actionAddrating(){
          $rating = new Rating();
          if($this->addRatingForm->load(Yii::$app->request->post()) && $this->addRatingForm->validate()){
           $rating->rating = $this->addRatingForm->rating;
           $rating->author_id = Yii::$app->user->id;
           $rating->user_id = $this->addRatingForm->user_id;
           try{
               $rating->save();
               return $this->redirect(Url::to(['select', 'id' => $this->addRatingForm->user_id]));
           }
           catch (Exception $ex){ return $this->refresh();}
        } 
        else{ return $this->goBack();}     
      }
}

views/bulletin/addBulletin.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
$this->title = 'Add new advert';
?>

<section class="container">
        <section class="col-md-offset-3 col-md-6 center-form">
         <?php Pjax::begin(['timeout' => 5000]); ?>
            <?php $form = ActiveForm::begin([
                             'id' => 'add-bulletin-form',
                             'method' => 'post',
                             'action' => ['bulletin/addbulletin'],
                             'options' => ['enctype'=>'multipart/form-data',
                                 'onsubmit' => 'return false',
                                 'data-pjax' => true],
                             'enableClientValidation' => true,
                              ]); ?>
                  <div class="form-group">
                    <label class="control-label col-xs-2">Title</label>
                    <div class="col-xs-10">
                       <?= $form->field($model, 'title')->label(false) ?>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="control-label col-xs-2">Description</label>
                    <div class="col-xs-10">
                       <?= $form->field($model, 'body')->textArea(['rows' => '6'])->label(false) ?>
                    </div>
                  </div>
                  <div class="form-group">
                        <label class="control-label col-xs-2">Price in $</label>
                        <div class="col-xs-10">
                            <?= $form->field($model, 'price')->label(false) ?>
                        </div>
                    </div>
                  <div class="form-group">
                    <label class="control-label col-xs-4">Title image</label>
                    <div class="col-xs-8">
                       <?= $form->field($model, 'title_image')->fileInput(['accept' => 'image/gif,image/jpeg,image/png'])->label(false) ?>
                    </div>
                  </div>
                
                  <div class="modal-footer">
                      <button type="submit" class="btn btn-primary" id="login-btn">Add</button>
                      <button type="reset" class="btn btn-default" data-dismiss="modal">Reset</button>
                  </div>

                 <?php ActiveForm::end(); ?>
            <?php Pjax::end(); ?>
        </section>
    </section>

views/bulletin/showBulletin.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\Html;
use app\logics\UserManager;
$manager = new UserManager();
$authorName = $manager->GetLoginById($bulletin->user_id);
$this->title = 'Bulletin '.$bulletin->id;
?>
    <div class="single-product-area">
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-md-10">
                    <div class="product-content-right">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="product-images">
                                    <div class="product-main-img">
                                        <?php echo Html::img('@web/uploads/'.$bulletin->title_image) ?>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-sm-6">
                                <div class="product-inner">
                                    <h2 class="product-name"><?php echo $bulletin->title ?></h2>
                                    <div class="product-inner-price">
                                        <ins>Price: $<?php echo $bulletin->price ?></ins> 
                                    </div>    
                                    
                                    <form action="" class="cart">
                                        <h4>Author: <?php echo $authorName; ?></h4>
                                        <?php echo Html::a("Connect with ".$authorName,['profile/select', 'id' =>$bulletin->user_id ] ,['data-pjax'=>0,"class"=>"add_to_cart_button"]) ?>
                                    </form>   
                                    
                                    <div class="product-inner-category">
                                        <h5>Date of adverting: <?php echo $bulletin->date ?></h5>
                                    </div> 
                                    <div role="tabpanel">
                                        <div class="tab-content">
                                            <div role="tabpanel" class="tab-pane fade in active" id="home">
                                                <h2>Product Description</h2>  
                                                <p><?php echo $bulletin->body ?></p> 
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>